# Train option
atari_id: "ALE/AirRaid-v5"
device: "mps"
seed: 42

# Hyperparameter
total_step: 5000000
replay_memory_size: 30000
batch_size: 32
skip_frame: 4

gamma: 0.99
start_epsilon: 1.0
end_epsilon: 0.1
anneal_step: 1000000

lr: 0.00025
momentum: 0.95
target_update_frequency: 5000

# Evaluation option
eval_every: 1000
eval_run: 5

record_play: true
record_episodes:
  - 1
  - 10
  - 100
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
  - 1200
  - 1400
  - 1600
  - 1800
  - 2000
  - 2500
  - 3000
  - 4000
  - 5000
  - 6000
  - 7000
  - 8000
